### ISSUE TITLE
Default thumbnail stopped working after discourse beta4 upgrade

### ISSUE THREAD

**Issue by iamaviator** [paviliondev/discourse-topic-previews#152]
Checked plugin global setting and at categories. Tried rebaking post, nothing seems to consider the default thumbnail url.

Discourse version 2.5.0.beta4 

Let me know if you need additional info.

**Comment by travelmassive** [comment]
Same for us - after upgrading all our thumbnails are lost.

**Comment by merefield** [comment]
Thumbnails are now generated by core Discourse.

See https://meta.discourse.org/t/topic-list-previews/101646/1023?u=merefield to bulk rebake posts.
